apiVersion: v1
kind: Service
metadata:
  name: tribeca-cep-ui
  labels:
    name: tribeca-cep-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30709
      name: tcp
  selector:
    run: tribeca-cep-ui
